name: Keep Fiverr Logged In

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  keep-online:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget unzip google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1-3)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Run Script
        run: |
          python3 fiverr_script.py
